name: SSH and Run Commands

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts

      - name: SSH to Server and Run Commands
        run: |
          ssh ubuntu@13.53.41.21 "whoami"
          ssh -o StrictHostKeyChecking=no -l ubuntu@13.53.41.21 'pwd'
