name: SSH Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SSH script
        run: |
          #ssh -o StrictHostKeyChecking=no -l ubuntu 13.53.41.21 'whoami'
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-13-53-41-21.eu-north-1.compute.amazonaws.com
          whoami
          pwd
